name: Deploy to Amazon EKS

on:
  push:
    tags:        
      - 'prd*'

env:
  AWS_REGION: ap-southeast-1                   
  ECR_REPOSITORY: wusd-openapi-backend         
permissions:
  contents: read

jobs:
  deploy:
    name: RUN CI build image
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
 
    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{  github.ref_name }}
      run: |
        docker build --build-arg VITE_ETH_RPC_URL=mainnet.infura.io --build-arg VITE_ETH_BLOCKCHAIN_URL=https://www.etherscan.io --build-arg VITE_API_BASE_URL=http://openapi.stabflow.app/api -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG . .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
